### ISSUE TITLE
space between target and colon

### ISSUE THREAD

**Issue by brccabral** [tadayosi/vscode-makefile-outliner#1]
Hi,
If the target has a space before the colon the outline is not detected.
This works:
```Makefile
all:
  .......
install:
  .......
clean:
  .......
```
This does not:
```Makefile
all :
  .......
install :
  .......
clean :
  .......
```

**Comment by tadayosi** [comment]
@brccabral Thanks for your feedback! It should be fixed with the released 0.2.0.
